(define (ends-in-vowel? wd)
  (member? (last wd) 'aeiou)
  )

(define (plural-first wd)
  ;; Ends in y - like boy or baby
  (if (equal? (last wd) 'y)
      (if (ends-in-vowel? (bl wd))
	  (word     wd  's)
	  (word (bl wd) 'ies)
	  )
      (word wd 's)
      )
  )

(define (ends-in-y?       wd) (equal? 'y (last wd)))
(define (ends-in-vowel-y? wd) (and (ends-in-y? wd)
				   (ends-in-vowel? (bl wd))))
(define (ends-in-x?       wd) (equal? 'x (last wd)))
(define (ends-in-z?       wd) (equal? 'z (last wd)))
(define (ends-in-zz?      wd) (and (ends-in-z? wd)
				   (ends-in-z? (bl wd))))

(define (plural wd)
  (cond ((ends-in-x?       wd) (word     wd  'es))
	((ends-in-zz?      wd) (word     wd  'es))
	((ends-in-z?       wd) (word     wd  'zes))
	((ends-in-vowel-y? wd) (word     wd  's))
	((ends-in-y?       wd) (word (bl wd) 'ies))
	(else                  (word     wd  's)))
  )

;;------------------------------------------------------------
(define (test-plurals)
  (cond ((not (equal? 'boxes   (plural 'box)))  '(Failed: box))
	((not (equal? 'buzzes  (plural 'buzz))) '(Failed: buzz))
	((not (equal? 'quizzes (plural 'quiz))) '(Failed: quiz))	
	((not (equal? 'boys    (plural 'boy)))  '(Failed: boy))
	((not (equal? 'babies  (plural 'baby))) '(Failed: baby))		
	(else '(Passed all tests - Hope they were adequate...)))
  )
