(define (vowel? wd)
  (cond ((member? 'a wd) #t)
	((member? 'e wd) #t)
	((member? 'i wd) #t)
	((member? 'o wd) #t)
	((member? 'u wd) #t)
	(else #f)
	)
  )

(define (gertrude wd)
  (let ((article (if (vowel? (first wd)) 'an 'a )))
    (se article	wd 'is article wd 'is article wd )
    )
  )
