(define (unspell wd)
  (cond ((member? wd 'abc)  '2)
	((member? wd 'def)  '3)
	((member? wd 'ghi)  '4)
	((member? wd 'jkl)  '5)	
	((member? wd 'mno)  '6)
	((member? wd 'pqrs) '7)
	((member? wd 'tuv)  '8)
	((member? wd 'wxyz) '9)	
	(else                wd))
  )

(define (phone-unspell wd)
  (accumulate word (every unspell wd))
  )
