(define (say letter)
  (cond ((equal? letter 'a) 'alpha)
	((equal? letter 'b) 'bravo)
	((equal? letter 'c) 'charlie)
	((equal? letter 'd) 'delta)
	((equal? letter 'e) 'echo)
	((equal? letter 'f) 'foxtrot)
	((equal? letter 'g) 'golf)
	((equal? letter 'h) 'hotel)
	((equal? letter 'i) 'india)
	((equal? letter 'j) 'juliett)
	((equal? letter 'k) 'kilo)
	((equal? letter 'l) 'lima)
	((equal? letter 'm) 'mike)
	((equal? letter 'n) 'november)
	((equal? letter 'o) 'oscar)
	((equal? letter 'p) 'papa)
	((equal? letter 'q) 'quebec)
	((equal? letter 'r) 'romeo)
	((equal? letter 's) 'sierra)
	((equal? letter 't) 'tango)
	((equal? letter 'u) 'uniform)
	((equal? letter 'v) 'victor)
	((equal? letter 'w) 'whiskey)
	((equal? letter 'x) 'xray)
	((equal? letter 'y) 'yankee)
	((equal? letter 'z) 'zulu)
	(else '(No Match))
	)
  )

(define (words wd)(every say wd))

;;------------------------------------------------------------
(define (test-words)
  (cond ((not (equal? '(charlie alpha bravo) (words 'cab))) '(failed - cab))
	(else '(Passed test))
	)
  )
